# Generated by Django 2.1.2 on 2019-02-03 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('building_unit', models.CharField(blank=True, max_length=1024, null=True)),
                ('building_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('street_number', models.CharField(max_length=32)),
                ('street_name', models.CharField(max_length=1024)),
                ('town', models.CharField(max_length=1024)),
                ('postcode', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
